#!/bin/bash
echo "=== AWS Resource Inventory (Project: SockShop) ==="
echo ""
echo "EC2 Instances:"
aws ec2 describe-instances --filters "Name=tag:Project,Values=SockShop" --query 'Reservations[*].Instances[*].[InstanceId,State.Name,InstanceType,PublicIpAddress]' --output table 2>/dev/null || echo "  None"
echo ""
echo "RDS Instances:"
aws rds describe-db-instances --query "DBInstances[?contains(DBInstanceIdentifier,'sockshop')].[DBInstanceIdentifier,DBInstanceStatus,Engine]" --output table 2>/dev/null || echo "  None"
echo ""
echo "Load Balancers:"
aws elbv2 describe-load-balancers --query "LoadBalancers[?contains(LoadBalancerName,'sockshop')].[LoadBalancerName,State.Code,DNSName]" --output table 2>/dev/null || echo "  None"
echo ""
echo "S3 Buckets:"
aws s3api list-buckets --query "Buckets[?contains(Name,'sockshop')].Name" --output text 2>/dev/null || echo "  None"
