apiVersion: v1
kind: Service
metadata:
  name: catalogue
  namespace: sock-shop
  labels:
    app: catalogue
spec:
  selector:
    app: catalogue
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
