apiVersion: v1
kind: Service
metadata:
  name: orders
  namespace: sock-shop
  labels:
    app: orders
spec:
  selector:
    app: orders
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
